/**
 * This package defines an interface and implementation for a query engine,
 * the application layer that interfaces the web service implementation with
 * the {@link ApplicationService} backend generated by the caCORE SDK.  
 */
package com.github.yacaqueryservice.engine;

